image:
  file: .gitpod.dockerfile
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - init: |
      yarn
      yarn build
      curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.2 python -
      poetry install
      poetry run python manage.py migrate
      poetry run python manage.py createcachetable
      poetry run python manage.py buildfixtures
      echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | poetry run python manage.py shell
      echo "CSRF_TRUSTED_ORIGINS = ['https://*.gitpod.io']" >> apps/guide/settings/local.py
    command: |
      cd /workspace/guide
      poetry run python manage.py runserver 0.0.0.0:8080
github:
  prebuilds:
    pullRequestsFromForks: true
vscode:
  extensions:
    - ms-python.python
